apiVersion: acmeplatform.com/v1alpha1
kind: AppClaim
metadata:
  name: platform-demo
  labels:
    app-owner: piotrzan
spec:
  parameters:
    namespace: devops-team
    connectionVariableName: AZURE_STORAGE_CONNECTION_STRING
    image: piotrzan/platform-demo:latest
    port: 3000
