apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-vcluster
  namespace: argocd
spec:
  destination:
    namespace: team2
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.15.0
    helm:
      values: |
        sync:
          fromHost:
            secrets:
              enabled: true
              mappings:
                byName:
                  # Sync the azure-creds secret from crossplane-system in the host
                  # to crossplane-system in the vCluster
                  "crossplane-system/azure-creds": "crossplane-system/azure-creds"
            ingressClasses:
              enabled: true
          toHost:
            ingresses:
              enabled: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true