apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teams-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc/api/v1/namespaces/team2/services/team2-vcluster:8443/proxy
    namespace: team2
  project: default
  source:
    repoURL: https://github.com/Piotr1215/infra-platform-arch
    path: teams-apps/team2
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true