---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-azure
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: default
      key: creds
