apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  package: xpkg.upbound.io/upbound/provider-azure-storage:v1.1.0
